PictureGallery/Models/ErrorViewModel.cs
using System;

namespace PictureGallery.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

PictureGallery/Models/Picture.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace PictureGallery.Models

{
    [Table("gallery")]
    public partial class Picture
    {
        [Key]
        [Column("ID")]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int ID { get; set; }
        [Required]
        [Column(TypeName = "varchar(50)")]
        public string Title { get; set; }
        [Required]
        [Column(TypeName = "varchar(75)")]
        public string FileName { get; set; }

    }
}

PictureGallery/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using PictureGallery.Models;

namespace PictureGallery.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        public IActionResult Test(string content)
        {
            ViewBag.Content = content;
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

PictureGallery/Controllers/PictureController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PictureGallery.Data;
using PictureGallery.Models;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace PictureGallery.Controllers
{
    public class PictureController : Controller
    {
        // GET: /<controller>/
        public IActionResult Index()
        {
            return RedirectToAction("List");
        }

        public IActionResult List()
        {
            DirectoryInfo uploadsDirectory = null;
            FileInfo[] files = null;

            try
            {
                string uploadsPath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/uploads");
                uploadsDirectory = new DirectoryInfo(uploadsPath);
                files = uploadsDirectory.GetFiles();
                ViewBag.Files = files;
            }
            catch (DirectoryNotFoundException e)
            {
                throw new Exception("Directory not found.");
            }
            catch (IOException e)
            {
                throw new Exception("Failed to access directory.");
            }
            

            return View();
        }

        public IActionResult Create(string title)
        {
            IActionResult action;

            if( User.Identity.IsAuthenticated )
            {
                action = View();
            }
            else
            {
                // if not logged in, redirect to gallery
                action = RedirectToAction("List");
            }
            return action;
        }

        [HttpPost]
        public async Task<IActionResult> Upload( string title, List<IFormFile> files)
        {

            title = title != null ? title.Trim() : null;
            bool validTitle = validateTitle(title);

            if(!validTitle)
            {
                ViewBag.Error = "You must include a title and it can be no more than 50 characters";
                ViewBag.Title = title;
                return View("Create");
            }

            if ( files.Count <= 0)
            {
                ViewBag.Error = "You must select a file to upload.";
                ViewBag.Title = title;
                return View("Create");
            }
            
            long size = files.Sum(f => f.Length);
            var filePaths = new List<string>();
            var pictureIDs = new List<int>();

            foreach (var formFile in files)
            {
                if( formFile.Length > 0)
                {
                    //For security reasons we want to rename the file
                    var oldFileName = Path.GetFileNameWithoutExtension(formFile.FileName);
                    var fileExtension = Path.GetExtension(formFile.FileName);
                    var newFileName = String.Concat(Convert.ToString(Guid.NewGuid()), fileExtension);

                    //upload the file to the uploads folder
                    var filePath = Path.Combine(Directory.GetCurrentDirectory(),"wwwroot/uploads", newFileName);
                    filePaths.Add(filePath);
                    using (var stream = new FileStream(filePath, FileMode.Create))
                    {
                        await formFile.CopyToAsync(stream);
                    }
                }
            }
            //return View("Create");
            return Ok(new { count = files.Count, size, filePaths, pictureIDs });
        }

        public bool validateTitle(string title)
        {
            var valid = true;

            if (string.IsNullOrWhiteSpace(title))
            {
                valid = false;
            }
            else
            {
                if (title.Length > 50)
                {
                    valid = false;
                }
            }

            return valid;
        }
    }
}

PictureGallery/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

PictureGallery/Views/Picture/Create.cshtml
@page
@{

}
<h1>Add Picture to Gallery</h1>


@{
    if (ViewBag.Success != null)
    {
        <p class="alert-success">@(ViewBag.Success)</p>
    }
    else if( ViewBag.Error != null)
    {
        <p class="alert-danger">@(ViewBag.Error)</p>
    }

}

    <form action="/Picture/Upload" method="post" enctype="multipart/form-data" id="form-picture-create">
        <label>
            Picture Title
            <input type="text" id="title" name="title" value="@(ViewBag.Title)" />
        </label>
        <label>
            Upload picture
            <input type="file" id="files" name="files" accept="image/png, image/jpg" multiple />
        </label>
        <input class="btn btn-primary" type="submit" value="Add picture" />
    </form>

PictureGallery/Views/Picture/List.cshtml
@page
@{
}
<h1>List Pictures</h1>

@if (User.Identity.IsAuthenticated)
{
    <p>You are logged in</p>
}

@if (!User.Identity.IsAuthenticated)
{
    <p>You are logged out</p>
}

@foreach(System.IO.FileInfo file in ViewBag.Files)
{
    <img src="~/uploads/@(file.Name)" />
}

PictureGallery/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PictureGallery</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/style.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PictureGallery</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Picture" asp-action="List">Gallery</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - PictureGallery - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>